# Generated by Django 3.2.4 on 2021-06-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=2137)),
                ('image', models.CharField(blank=True, max_length=256)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('command', models.CharField(max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.shopcategory')),
            ],
        ),
    ]
