# Generated by Django 3.2.4 on 2021-06-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotPay', '0002_remove_hotpaypayment_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaypayment',
            name='item_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
