# Generated by Django 3.2.4 on 2021-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotPay', '0003_remove_hotpaypayment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaypayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
