# Generated by Django 3.2.4 on 2021-06-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotPay', '0003_hotpaypayment_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotPayPayment',
        ),
    ]
