# Generated by Django 3.2.4 on 2021-06-19 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HotPay', '0004_hotpaypayment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpaypayment',
            name='email',
            field=models.CharField(default='Brak', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotpaypayment',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotpaypayment',
            name='HotPay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotPay.hotpay'),
        ),
    ]
