# Generated by Django 3.2.4 on 2021-06-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rcon', models.BooleanField(default=False)),
                ('rcon_host', models.BooleanField(blank=True, max_length=255, null=True)),
                ('rcon_port', models.IntegerField(blank=True, null=True)),
                ('rcon_password', models.BooleanField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
