# Generated by Django 3.2.4 on 2021-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerConnection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconnection',
            name='rcon_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='rcon_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
