# Generated by Django 3.2.4 on 2021-06-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerConnection', '0002_auto_20210630_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverconnection',
            old_name='user_rcon',
            new_name='use_rcon',
        ),
    ]
